// unbound.go -- generate unbound.conf fragment
//
// License GPLv2

package main

import (
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/opencoff/unbound-adblock/internal/blacklist"
)

func unboundOut(b *blacklist.BL, fd io.Writer) {
	v := make([]string, 0, len(b.Hosts)+len(b.Domains))

	f := func(out, in []string) []string {
		for _, v := range in {
			z := fmt.Sprintf(`   local-zone: "%s" static`, v)
			out = append(out, z)
		}
		return out
	}

	v = f(v, b.Domains)
	v = f(v, b.Hosts)

	fmt.Fprintf(fd, `# Unbound config: ad domains and malware domains
#
# Auto-generated by %s on %s
# Total domains: %d, total hosts %d
#
# --- DO NOT EDIT --
server:
%s

# - EOF
`, os.Args[0], time.Now(), len(b.Domains), len(b.Hosts), strings.Join(v, "\n"))
}
